import type { Metadata } from "next";
import { Mulish } from "next/font/google";
import "./globals.css";
import { headers } from "next/headers";
import { auth } from "@/lib/auth";
import LenisProvider from "@/components/LenisProvider";
import { Toaster } from "sonner";

const roboto = Mulish({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800", "900", "1000"],
  variable: "--font-roboto",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth.api.getSession({
    headers: await headers(),
  });

  return (
    <html lang="tr" className={roboto.variable}>
      <body className={`${roboto.className} antialiased h-screen bg-body`}>
        {children}
        <Toaster />
      </body>
    </html>
  );
}
